- kernel/generic/src/ddi/ddi.c
When an uspace app requests to map 0 bytes, dmamem_map_anonymous calls
frame_alloc, which asserts the size is not zero, causing kernel panic.
> ddi: do not assume arguments are correct

- .travis.yml
Any objections of having `.travis.yml` with [Travis CI](https://travis-ci.org/) configuration? The configuration is a very basic one that only builds for all architectures. Unlike [our CI](http://ci.helenos.org) Travis does not provide any downloadable artifacts but Travis can be run on forks and also on pull requests.
We might add building of ports later but I am not sure if we would be able to fit into the 2h limit.
> Use Travis CI for per-commit builds

- uspace/lib/c/generic/async.c
I somehow feel this must be based on wrong assumptions, because otherwise it wouldn't be done this way. Feel free to reject if so.
> async_usleep: no need to use a heap-allocated amsg_t

- .travis.yml
- tools/travis.sh
This PR contains several improvements of the CI process. The dashboard is less cluttered as less variables are set (see [here](https://travis-ci.org/vhotspur/helenos/builds/332773178)). Ported software is built too. But only for `ia32` as that seems to be the most healthy platform in this context. Overall, this should provide shorter feedback than the [nightly builds](http://ci.helenos.org).
Due to complexity of the building process (especially when ported software is compiled) a separate script is used with Travis CI to control the build. See comments in `.travis.yml` for details how to customize what is being built (if you plan to use it on your feature branches).
Okay to merge this?
> Travis CI improvements

- uspace/lib/drv/generic/driver.c
Even though the permanent reference held by the device being added is
dropped correctly, the temporary reference added by remove/gone is not.
That caused leaking devices and parent sessions along with them (which
is the way we discovered it).
> libdrv: fix leaking ddf_dev_t reference

- Makefile
- tools/autotool.py
- uspace/Makefile
- uspace/Makefile.common
- uspace/lib/c/arch/amd64/Makefile.common
- uspace/lib/posix/Makefile
without necessarily knowing anything about the build system.
Not yet ideal in terms of forward compatibility, so I expect some small changes will be necessary, but I'm fairly comfortable with this level of abstraction. The main repository doesn't need to know anything about ports, and ports don't need to know anything particular about HelenOS (except where to look for the configuration).
> Generate files that a third party can use to build software for HelenOS

- kernel/arch/amd64/src/amd64.c
- kernel/arch/ia32/src/ia32.c
- kernel/arch/ia64/src/ia64.c
- kernel/arch/sparc64/src/drivers/kbd.c
- kernel/genarch/include/genarch/drivers/ns16550/ns16550.h
- kernel/genarch/src/drivers/ns16550/ns16550.c
Some UART controllers are compatible with 16550A, but have more spacing
between registers. In particular, ARMADA 385, which is the basis of
Turris Omnia router, has a compatible UART with 32b registers instead of 8b
(with the top three bytes unused).
Note: The device tree file hints that some UARTs may need register reads/writes
that are wider than 8 bits, and this commit does not address that possibility.
> Generalize ns16550 driver to work with more chips.

- uspace/lib/c/arch/abs32le/src/fibril.c
- uspace/lib/c/arch/amd64/src/fibril.S
- uspace/lib/c/arch/arm32/src/fibril.S
- uspace/lib/c/arch/ia32/src/fibril.S
- uspace/lib/c/arch/ia64/include/libarch/fibril.h
- uspace/lib/c/arch/ia64/src/fibril.S
- uspace/lib/c/arch/mips32/src/fibril.S
- uspace/lib/c/arch/ppc32/src/fibril.S
- uspace/lib/c/arch/riscv64/src/fibril.c
- uspace/lib/c/arch/sparc64/src/fibril.S
- uspace/lib/c/generic/context.c
- uspace/lib/c/generic/setjmp.c
- uspace/lib/c/include/context.h
- uspace/lib/c/include/setjmp.h
Since they already _almost_ are identical, this just closes the tiny gap and removes an ugly hack from the standard library in the process.
The assembly changes need to be reviewed by more eyes though.
> Turn context_save/context_restore into standard setjmp/longjmp.

- .travis.yml
- tools/travis.sh
This adds a ccheck job to Travis CI. The job will currently only fail if ccheck cannot parse a source file. This can happen either if the file has broken syntax, one of the few specific style issues mentioned in ccheck''s README.md or if it tries to use a macro to extend the C syntax in a way other than those explicitly supported.
> Add Ccheck to Travis CI

- tools/autotool.py
- tools/toolchain.sh
Instead of maintaining patches separately, directly pull sources from git.
The target is, at the moment, still opt-in.
> Revive support for `-helenos` target specification.

- uspace/drv/nic/ar9271/ar9271.c
This commit might fix Trac ticket #628. I don't have the hw and don't know how to test this in QEMU (the device seems unsupported as of QEMU 2.12).
> ar9271: Set cable state according to connectedness

- uspace/lib/c/generic/async/server.c
- uspace/lib/c/generic/fibril.c
- uspace/lib/c/include/async.h
- uspace/lib/c/include/fibril.h
Instead of running notification handlers in the same fibril that received it,
forcing us to allocate a new fibril when the handler blocks, we instead queue
the notifications, and allow an arbitrary but fixed number of dedicated fibrils
handle them.
Although a service can increase the number of handler fibrils to reduce latency,
there are now no dynamic allocations due to received notifications.
When the same notification is received again while the older instance is still
in queue, the new notification overwrites the old and increments a counter
of received notifications.
The counter is currently unused, because passing it to the handler would
require extensive changes to user code, but it should be straightforward
to make use of it should the need arise.
> Add notification queue to the async framework.

- .gitignore
- HelenOS.config
- contrib/tools/random_check.sh
- tools/autotool.py
- tools/toolchain.sh
- tools/travis.sh
- uspace/lib/posix/Makefile
As previously discussed, utilizing the compiler-provided headers and libraries would allow us to avoid a number of problems and reduce the amount of architecture-support code that we have to implement ourselves. With this change, the support for using Linux-targeted toolchain, or even the host toolchain itself, is removed, due to the inherent issues caused by such setup.
Additionally, the toolchain installation is a bit simplified to install all targets into a single prefix. This prefix can be added to the `PATH` so that one can simply execute e.g. `amd64-helenos-gcc` instead of needing to use the whole path.
> Switch completely to HelenOS-specific toolchain target.

- kernel/arch/abs32le/include/arch/asm.h
- kernel/generic/include/arch.h
- kernel/generic/include/cpu.h
- kernel/generic/include/mm/as.h
- kernel/generic/include/preemption.h
- kernel/generic/include/proc/task.h
- kernel/generic/include/proc/thread.h
- kernel/generic/include/synch/rcu.h
- kernel/generic/include/time/timeout.h
- kernel/generic/src/debug/panic.c
- kernel/generic/src/main/main.c
- kernel/generic/src/proc/scheduler.c
- kernel/generic/src/proc/the.c
- kernel/generic/src/proc/thread.c
- kernel/generic/src/synch/rcu.c
Because the word "THE" occurs several times in every licence
header, searching for occurences of "THE" macro is more difficult
than necessary.
While I appreciate the wit of it, using a nonconflicting word
for it is more practical.
> Rename THE/the_t to CURRENT/current_t

- kernel/generic/src/mm/as.c
- kernel/generic/src/proc/task.c
Commit 78de83de52a9115dc77b09bb7029403dad8c2fb0 changed the way how
reference counting works for newly created objects, but didn't remove
the explicit bumping of reference count for address spaces, which had
been necessary before that. Because of that, as_t structures were never
deallocated.
> Fix as_t reference counting

- boot/Makefile
- tools/autotool.py
This PR adds `crt*.o` files and `libgcc.a` to the generated image when `CONFIG_DEVEL_FILES` is set so we can compile again inside HelenOS ([this bug](http://www.helenos.org/ticket/750)) (another PR for harbours will be opened shortly).
The change is rather big because it has to find `libgcc.a` which is somewhere in `$CROSS_PREFIX`.
@le-jzr does it make sense to do it like this? Thanks!
> Add missing libs to image.iso

- uspace/srv/devman/driver.c
Commit b25970fdaa left the drv uninitialized. From the description and the way it is used in the code I infer it should have been initialized to node->drv. Please check.
> Fix use of uninitialized variable

- kernel/Makefile
- kernel/generic/include/bitops.h
- kernel/generic/include/main/main.h
- kernel/generic/include/mm/slab.h
- kernel/generic/src/main/main.c
- kernel/generic/src/mm/malloc.c
- kernel/generic/src/mm/slab.c
This new implementation places the allocation size in front of the allocated
object, instead of relying on the slab allocator being able to determine source
slab cache for an object. This should improve scalability and help reduce
complexity of the memory management subsystem (further changes coming).
The drawback is more memory consumed by small malloc() allocations, however that
can be mitigated by switching to an API where the user provides known object
size to deallocation (most users know it either statically or from length they
necessarily remember).
> Modify kernel malloc()

- uspace/app/mkext4/mkext4.c
Also adds the --help parameter.
> mkext4: fix infinite loop when passing an invalid argument.

- uspace/app/sysinst/sysinst.c
\hw\pci0 has been replaced by \w\sys
This fixes commit b25970fdaa53055fe44afdf414204a77d77efbf1
> sysinst: fix the default dev path

- uspace/lib/ext4/src/filesystem.c
I hit an assert in free() when opening an invalid ext4 filesystem,
this was due to a bug in ext4_filesystem_open().
In case of error, it called ext4_filesystem_fini() against an
uninitialized filesystem instance.
> libext4: fix double free in case ext4_filesystem_open() fails.

- tools/toolchain.sh
Adds a new flag for testing the installed version against the version in toolchain.sh. This has been requested by the ticket #569.
./tools/toolchain.sh --test-version
./tools/toolchain.sh --test-version all
./tools/toolchain.sh --test-version ia32
> Ticket 569

- uspace/lib/cpp/include/__bits/adt/list.hpp
- uspace/lib/cpp/include/__bits/complex.hpp
- uspace/lib/cpp/include/__bits/functional/bind.hpp
- uspace/lib/cpp/include/__bits/io/fstream.hpp
- uspace/lib/cpp/include/__bits/io/istream.hpp
- uspace/lib/cpp/include/__bits/io/ostream.hpp
- uspace/lib/cpp/include/__bits/new.hpp
- uspace/lib/cpp/include/__bits/string/string.hpp
- uspace/lib/cpp/include/__bits/thread/future.hpp
- uspace/lib/cpp/include/cassert
- uspace/lib/cpp/src/__bits/runtime.cpp
- uspace/lib/cpp/src/__bits/unwind.cpp
- uspace/lib/cpp/src/condition_variable.cpp
- uspace/lib/cpp/src/string.cpp
- uspace/lib/cpp/src/thread.cpp
As discussed with @le-jzr , I added a macro that is used in unimplemented functions to abort the program and report the source code location.
There were some cases ignored:
- rbtree: the missing functions are meant to be no-op (it's missing balancing operations, but the
structure works without them)
- locale: these functions modify their input to another localization (e.g. encoding), but they are stubs
- constexpr functions: these can't be done without implementation or removal, there were two cases:
- string.hpp: does not matter, their return value is valid
- limits.hpp: 3 floating point functions, I will look for a fix (or remove them)
Also added missing include in <new> and a missing symbol needed for the runtime (it was part of the custom linker scripts which are now gone).
> Abort and report when an unimplemented function is called

- uspace/lib/c/generic/async/client.c
- uspace/lib/c/generic/async/server.c
- uspace/lib/c/include/async.h
- uspace/srv/devman/main.c
- uspace/srv/fs/locfs/locfs_ops.c
- uspace/srv/locsrv/locsrv.c
- uspace/srv/ns/clonable.c
- uspace/srv/ns/service.c
- uspace/srv/vfs/vfs_ops.c
"fast" and "slow" paths are implementation detail.
All macros in <async.h> are turned into external functions, so that
this implementation detail doesn't leak. Additionally, removing macros is
A Good Thing on its own, e.g. helping C++ interoperability.
> Remove async "fast" and "slow" functions from public interface

- uspace/lib/c/arch/arm32/src/syscall.c
- uspace/lib/c/arch/mips32/src/syscall.c
- uspace/lib/c/arch/ppc32/src/syscall.c
As the syscall may touch arbitrary memory, we need to prevent the compiler to cache some values in registers.
Actual problem was demonstrated on Kalisto during school assignments (thanks Adam Frey) but HelenOS uses basically the same code, thus the issue applies here too.
Can someone better versed with other architectures check that this does not apply to them as well?
> mips32: clobber memory on sycall

- abi/include/abi/cap.h
- abi/include/abi/ddi/arg.h
- abi/include/abi/elf.h
- abi/include/abi/ipc/interfaces.h
- abi/include/abi/ipc/ipc.h
- abi/include/abi/ipc/methods.h
- abi/include/abi/kio.h
- abi/include/abi/mm/as.h
- abi/include/abi/synch.h
- abi/include/abi/sysinfo.h
- uspace/app/taskdump/symtab.c
- uspace/lib/c/generic/rtld/symbol.c
Builds upon PR#157, converting most of the macros present in `abi/` to C language constructs.
> [RFC] Do not use preprocessor macros in `abi/`

- kernel/genarch/src/mm/page_ht.c
- kernel/generic/include/adt/hash_table.h
- kernel/generic/src/adt/hash_table.c
- kernel/generic/src/cap/cap.c
- kernel/generic/src/ddi/irq.c
- kernel/generic/src/lib/ra.c
- uspace/app/hbench/env.c
- uspace/app/trace/ipcp.c
- uspace/app/trace/proto.c
- uspace/lib/block/block.c
- uspace/lib/c/generic/adt/hash_table.c
- uspace/lib/c/generic/async/ports.c
- uspace/lib/c/generic/async/server.c
- uspace/lib/c/include/adt/hash_table.h
- uspace/lib/ext4/src/ops.c
- uspace/lib/nic/src/nic_addr_db.c
- uspace/lib/nic/src/nic_wol_virtues.c
- uspace/srv/devman/devtree.c
- uspace/srv/fs/cdfs/cdfs_ops.c
- uspace/srv/fs/exfat/exfat_idx.c
- uspace/srv/fs/fat/fat_idx.c
- uspace/srv/fs/locfs/locfs_ops.c
- uspace/srv/fs/mfs/mfs_ops.c
- uspace/srv/fs/tmpfs/tmpfs_ops.c
- uspace/srv/fs/udf/udf_idx.c
- uspace/srv/hid/input/gsp.c
- uspace/srv/ns/service.c
- uspace/srv/ns/task.c
- uspace/srv/vfs/vfs_node.c
The assumption here is that modifying key in the hash/equal functions in something completely unexpected, and not something you would ever want to do intentionally, so it makes sense to disallow it entirely to get that extra level of checking.
> Indicate and enforce constness of hash table key in certain functions

- README.md
Built on Fedora 29 and Ubuntu 18.10. Both packages needed to be installed otherwise the toolchain.sh would fail.
> Added flex and bison as build deps

- .gitignore
- boot/arch/arm64/src/main.c
- kernel/arch/arm64/src/interrupt.c
- tools/ew.py
A few clean-up patches to address review comments in https://github.com/HelenOS/helenos/pull/165.
Note: The second patch in the series unifies firmware search in `tools/ew.py` for arm64 and sun4v. It changes the script to first search for firmware binaries by checking an environment variable, `EW_QEMU_EFI_AARCH64` for arm64 and `OPENSPARC_BINARIES` for sun4v. If this fails then the script tries finding the binaries in their expected default locations. If this also fails then an error is reported on stderr and the script exits.
However, I'm thinking this might not be the best approach. Perhaps, it would be better to introduce a similar scheme to how the HelenOS toolchain is searched first in `CROSS_PREFIX` and then `/usr/local/cross/`.
In case of `tools/ew.py`, firmware binaries could be …
> AArch64 post-merge clean up

- uspace/app/bdsh/compl.c
- uspace/app/bdsh/exec.c
- uspace/app/bdsh/util.c
- uspace/app/bdsh/util.h
Based on #147 
- Allows to execute subdirectories from search_path and to autocomplete them
- prevents execution from the working directory and autocompletion if not specified with ./ ../ or /
> Ticket 684 improved

- kernel/generic/include/lib/elf_load.h
- kernel/generic/include/proc/program.h
- kernel/generic/src/lib/elf.c
- kernel/generic/src/main/kinit.c
- kernel/generic/src/proc/program.c
- uspace/lib/c/generic/dlfcn.c
- uspace/lib/c/generic/elf/elf_load.c
- uspace/lib/c/generic/elf/elf_mod.c
- uspace/lib/c/generic/rtld/module.c
- uspace/lib/c/generic/rtld/rtld.c
- uspace/lib/c/include/elf/elf_load.h
- uspace/lib/c/include/elf/elf_mod.h
- uspace/lib/c/include/rtld/module.h
- uspace/srv/loader/main.c
- corrects a null pointer failure in dlopen()
- prevents lib/rtld to call exit()
- corrects lib/elf to return errno_t instead of it's own error codes
> Cleanup lib rtld&elf

- uspace/app/usbinfo/main.c
This patch fix a typo into usbinfo usage message:
"-r  --hid-report-usages" must be replaced to "-R --hid-report-usages"
> Fix usbinfo utility usage message typo.

- meson/part/extra_targets/meson.build
- meson/part/tools/meson.build
Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives). 
The original name of this program was "C++check", but it was later changed to "Cppcheck".
Despite the name, Cppcheck is designed for both C and C++.
To run target just type:
ninja cppcheck > /dev/null
Note: There is a problem with memory.cpp so cppcheck analysis ends about 30% completed.
[helenos_cppcheck_without_memory.cpp.txt](https://github.com/HelenOS/helenos/files/4312297/helenos_cppcheck_without_memory.cpp.txt)
> Add cppcheck extra target to allow static analysis.

- uspace/drv/nic/e1k/e1k.c
To prevent false interrupt claims when masked-out ICR causes are true.
> Mask the ICR register in the e1k interrupt claim

- kernel/arch/arm32/src/mach/raspberrypi/raspberrypi.c
- kernel/genarch/include/genarch/drivers/bcm2835/mbox.h
- kernel/genarch/src/drivers/bcm2835/mbox.c
Currently, the SPARTAN kernel assumes a display size of 640x480
With this patchset, it will read the correct size from VideoCore,
looks much better on large screens.
http://bsdbackstore.it/misc/IMG_3463.jpg
> Graphics improvements for the Raspberry PI

- kernel/arch/amd64/src/amd64.c
- kernel/arch/ia32/src/ia32.c
- kernel/genarch/include/genarch/drivers/ns16550/ns16550.h
- kernel/genarch/src/drivers/ns16550/ns16550.c
Currently, the NS116550 serial line controller is left with its settings as it was left by the boot firmware and/or bootloader.  On my computer, this was an invalid configuration, and it left me with a really slow booting system, since each output character had to go through the full timeout loop in ns16550_sendb().
This patch adds the necessary bit and register descriptions to configure the baud rate and transmission settings, as well as configuring them on initialization, currently with values matching the ns8250 userspace character device driver (38400 baud, 8-bit words, 2 stop bits, no parity).
This could perhaps be changed to be adjustable with a kernel command-line argument, or through the configuration system.
This change does not affect emulators, since those largely ignore these …
> Configure NS16550 transmission format settings on initialization.

- kernel/arch/arm32/include/arch/mm/page.h
- kernel/arch/arm32/src/cpu/cpu.c
* enable the icache and branch prediction for ARMv6
* flush the branch predictor after writing to the TTBR0 register
Before: https://www.youtube.com/watch?v=OiGDSs6Yb6A
After: https://www.youtube.com/watch?v=JThq4GNtN2E
> arm32: performance boost on raspberry pi

- uspace/lib/ext4/src/extent.c
For partial release of first extent, first_fblock > start of extent, this fix makes delete_count smaller than block_count instead of larger as it should be.
> Fix partial release of first extent

- kernel/generic/include/cpu.h
- kernel/generic/include/time/timeout.h
- kernel/generic/src/time/clock.c
- kernel/generic/src/time/timeout.c
Replaces countdown with an immutable deadline, which allows us to remove `timeout->lock` and simplify the code quite a bit.
> Simplify timeout implementation in kernel

- configure.sh
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
> Fixed warning

- tools/conf/msim.conf
- tools/ew.py
I assume we do not need to keep backward compatibilty and support both pre and post 2.0 versions of MSIM.
> Updates for MSIM >2.0.0

- uspace/lib/c/generic/rndgen.c
- uspace/lib/c/generic/uuid.c
- uspace/lib/c/include/rndgen.h
- uspace/lib/c/include/types/uuid.h
- uspace/lib/c/include/uuid.h
- uspace/lib/c/test/uuid.c
- uspace/lib/label/src/gpt.c
Change the UUID internal representation so that it has named fields.
Encode the partition type UUID in little-endian format so that the type of GPT partition created within HelenOS can be recognized outside of HelenOS.
I haven't found anything regarding the byte order in the UEFI spec, but this is the way it is done.
sections[1]:
- time_low, time_mid, time_hi_and_version are stored in little-endian
- clock_seq_hi_and_reserved, clock_seq_low, node are stored in big-endian.
Actually it is all little-endian, but because of missing hyphens it appears that the second half is big-endian. [2] [3]
[1] https://www.rfc-editor.org/rfc/rfc4122#section-4.1.2
[2] https://en.wikipedia.org/wiki/Universally_unique_identifier#Encoding
[3] https://devblogs.microsoft.com/oldnewthing/20220928-00/?p=107221
> Change internal UUID representation and use correct GPT UUID endianness

- kernel/generic/include/debug.h
When "Detailed kernel logging" is enabled, HelenOS won't compile showing the following error message:
`../../helenos/kernel/generic/src/main/main.c: In function 'main_bsp_separated_stack':                                                   
../../helenos/kernel/generic/include/debug.h:62:21: error: implicit declaration of function 'symtab_fmt_name_lookup' [-Werror=implicit-$
unction-declaration]                                                                                                                    
62 |                     symtab_fmt_name_lookup(CALLER), __FILE__, __LINE__, \                                                       
|                     ^~~~~~~~~~~~~~~~~~~~~~ …
> Make HelenOS compilable when detailed kernel logging is enabled

- common/adt/bitmap.c
- common/include/adt/bitmap.h
- uspace/lib/c/meson.build
Hi,
I happen to need to use a bitmap for my project, but the one in HelenOS is
not available in libc, only for the kernel...
So I included it to be built in libc, but then userspace doesn't see <[typedefs.h](https://github.com/HelenOS/helenos/blob/master/kernel/generic/include/typedefs.h)>
kernel header, which seems to not be needed by the bitmap.
Objections? Ok?
> Allow bitmap to be used in userspace

- uspace/lib/ata/src/ata.c
While browsing the ATA code again, I noticed that the initial call to calloc() doesn't have a free() pair.
> ata_channel_destroy(): free the channel

- uspace/lib/c/generic/rtld/module.c
- uspace/lib/c/generic/thread/tls.c
Before this patch, `_tcb_data_offset` always used `__progsymbols.elfstart`. However, that is wrong when it is being called from the loader server!! This can leave much less space for the TLS data than requested and TLS accesses will corrupt some memory!
Now we pass to it a pointer to the correct ELF, falling back to elfstart in the public tls_get call.
Also added some comments, explaining some confusing parts...
> fix calculation of TLS size for main fibril

- uspace/app/dltest/dltest.c
- uspace/lib/c/generic/elf/elf_load.c
- uspace/lib/c/generic/libc.c
- uspace/lib/c/generic/rtld/module.c
- uspace/lib/c/generic/rtld/rtld.c
- uspace/lib/c/generic/thread/tls.c
- uspace/lib/c/include/rtld/module.h
- uspace/lib/c/include/rtld/rtld.h
- uspace/srv/loader/main.c
Another TLS issue, surprisingly completely unrelated to #240
This is about running static binaries, but with CONFIG_RTLD enabled
Let's look at the loader code:  
(just keep the code links for reference, I explain the sequence below)
https://github.com/HelenOS/helenos/blob/eff458dc0610e2e236a23436d7688091d3843237/uspace/srv/loader/main.c#L288-L317
The `elf_load` call:
https://github.com/HelenOS/helenos/blob/eff458dc0610e2e236a23436d7688091d3843237/uspace/lib/c/generic/elf/elf_load.c#L57-L87
So, the when the loader is started and runs ldr_load, it first loads the ELF with `elf_load`. After loading the file, for static binaries, `elf_load` simply fills `prog_info.env = NULL`, and `rtld_prog_process` is not called.
So afterwards, back in `ldr_load`, `env == NULL` means that `tls_make` will be …
> init RTLD runtime at load time even for statically linked binaries

- kernel/arch/amd64/src/asm.S
- uspace/app/tester/mm/mapping1.c
In the `/app/tester`'s `mapping1` test case, `NULL` is passed into the `as_get_physical_mapping` syscall.
This results in the syscall correctly returning `EPERM`, as down the call stack the return value is determined by
```c
// uspace_dst is our incoming NULL
rc = !memcpy_to_uspace(uspace_dst, src, size) ? EPERM : EOK;
```
(as `memcpy_to_uspace` returns `0` on failure) and the (unexpected) failure of the test case.
As this use of the syscall (passing `NULL` as the only `out` argument) is not reflective of real usage, 
I only adjusted the call site. I also fixed a comment in the assembly which seems incorrect according 
to System V x86-64 ABI.
> fix incorrect syscall usage in tester/mapping1 test

- uspace/app/blkdump/blkdump.c
Previous if conditions might increment `argv`, and the next conditions can dereference the dereference `*(*argv)` (in`str_cmp`) without checking.
Reproduce crash: for example: `blkdump --offset 16`
> uspace/app/blkdump: fix argv null deref
